Add -o flag to update integration manifest with retrieved store type definition
Keyfactor/kfutil pull request #109
Opened 2023-11-03 21:10 UTC by m8rmclaren

- Add `-o | --output-to-integration-manifest` flag to output retrieved store type to an Integration Manifest.
  - If manifest exists, store type is appended to store type list
  - If manifest exists and a store type with the same name is already present, the contents are overwritten with what Command returned.
  - If the manifest doesn't exist, it's created and populated _only_ with the schema and the store type definition.
- Refactored `store-type get` path to implement the `flags.Flags` and `flags.Options` interfaces.

2023-11-06 19:00 UTC, spbsoluble requested changes

2023-11-07 21:34 UTC, m8rmclaren commented on cmd/storeTypes_get.go
> +func NewStoreTypesGetFlags() *StoreTypesGetFlags {
Resolved in 3a6be4cf7c543184cc0120e18046a57349c58b4d

2023-11-07 21:39 UTC, m8rmclaren reviewed
Thanks for the feedback

2023-11-07 21:39 UTC, m8rmclaren commented on cmd/storeTypes_get.go
> +func NewCmdStoreTypesGet() *cobra.Command {
`NewCmdStoreTypesGet` is synonymous with "Instantiate a Store Types Get Cobra command" - I could change it to `CreateCmdStoreTypesGet`?

2023-11-07 21:39 UTC, m8rmclaren commented on cmd/storeTypes_get.go
> +func NewCmdStoreTypesGet() *cobra.Command {
Resolved in a1cb13c330f5d4475d0867a96a6d926f4d06c4aa

2023-11-08 19:30 UTC, spbsoluble requested changes
Please regenerate the docs and fix the test that is failing: https://github.com/Keyfactor/kfutil/actions/runs/6802999075/job/18497341205#step:3:93

I suspect you might need to add another couple tests as well:

1. `kfutil store-types get --name $NAME -g` no write to file
2. `kfutil store-types get --name $NAME -g -o $VALID_MANIFEST_FILE`
3. `kfutil store-types get --name $NAME -g -o $INVALID_FILE`

2023-11-09 21:32 UTC, m8rmclaren commented
> Please regenerate the docs and fix the test that is failing: https://github.com/Keyfactor/kfutil/actions/runs/6802999075/job/18497341205#step:3:93
> 
> I suspect you might need to add another couple tests as well:
> 
> 1. `kfutil store-types get --name $NAME -g` no write to file
> 2. `kfutil store-types get --name $NAME -g -o $VALID_MANIFEST_FILE`
> 3. `kfutil store-types get --name $NAME -g -o $INVALID_FILE`

When output to manifest (`--output-to-integration-manifest`) is present, the generic format flag is automatically set. This behavior is noted in the usage.

```go
	// Set the output type to full unless genericFormat is true
	f.outputType = "full"
	if f.genericFormat {
		f.outputType = "generic"
	}

	// If outputToIntegrationManifest is true, set the output type to generic
	if f.outputToIntegrationManifest {
		f.outputType = "generic"
	}
```

`get [-i <store-type-id> | -n <store-type-name>] [-b <git-ref>] [-g | --output-to-integration-manifest]`

2023-11-16 22:16 UTC, spbsoluble approved these changes

2023-11-17 19:48 UTC, merged